version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      #folder files of database id mapped in local machine
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:3000
      #local:container machine
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://root:root@cluster0.po7oseu.mongodb.net/Recipes?retryWrites=true&w=majority
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
  